CREATE DATABASE IF NOT EXISTS login;
USE login;
CREATE TABLE IF NOT EXISTS usuario (
  usuario_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(100) NOT NULL,
  senha VARCHAR(100) NOT NULL,
  nome VARCHAR(100) NOT NULL,
  data_cadastro DATETIME NOT NULL);
SELECT * FROM usuario;